### PR TITLE
Geoserver: new layer and updated style

### PR DESCRIPTION
**Pull request by richardforsterNVBW**
# Changes
## Parking
* added new layer `MobiData-BW:parking_sites_item` 
* added `purpose` attribute to layer `MobiData-BW:parking_sites_bicycle` 
* changed position of existing `purpose` attribute in `MobiData-BW:parking_sites` 
## Sharing
* added `teilauto_neckar-alb` for non-realtime data  in style `MobiData-BW:mdbw_sharing_stations_default`

### CODE REVIEW

**Review by hbruch — CHANGES_REQUESTED** [review]
Looks mostly good to me. However, capacity is a required attribute and should not be reported as nillable, no?

And at least for some attributes like e.g. `max_height`, a description would be helpful so users are aware of the units returned.

**Comment by richardforsterNVBW** [comment]
> Looks mostly good to me. However, capacity is a required attribute and should not be reported as nillable, no?
> 
> And at least for some attributes like e.g. `max_height`, a description would be helpful so users are aware of the units returned.

I found several other required attributed which were falsely reported as optional as `type` or `static_data_updated_at`. I fixed it and squashed the commits into one.

I will prepare another commit for next week which will also include descriptions for the parking layers.

I found that the new parking_sites_item layer's `featuretype.xml` did not include a list of the attributes with infos on optional/required, name, nillable and so on. For the new squashed commit I added it manually. Does GeoServer not create the `featuretype.xml` automatically with a list of the attributes?

**Review by hbruch — APPROVED** [review]
LGTM.

No, you explicitly need to check the option, otherwise the schema is deduced from the table schema.

**Comment by richardforsterNVBW** [comment]
> LGTM.
> 
> No, you explicitly need to check the option, otherwise the schema is deduced from the table schema.

This means, that I need to update the attribute list when new attributes are added via SQL statement, since it is not automatically added to `<attributes>`?

**Pull request merged**
