### PR TITLE
fixed the formatting of stops sld

### PR DESCRIPTION
**Pull request by richardforsterNVBW**
fixed the formatting of the sld file

### CODE REVIEW

**Review by hbruch — APPROVED** [review]
LGTM

**Comment by hbruch** [comment]
This PR seems to include the changes of #98, also?

**Comment by richardforsterNVBW** [comment]
Yes. I created a new branch since #98 was already behind. I should have pushed the changes to #98 instead? What is the procedure?

**Comment by hbruch** [comment]
OK. Could you close #98 then? Another option would have been to rebased #98 on the latest commit on main, and force push the original branch again. And then add the reformat as separate commit. Usually, reformatting and functional changes should go to separate commits, so others can easily follow what changed, but never mind.

**Comment by richardforsterNVBW** [comment]
I can close it.

For documentation purpose:

> We did not use xmllint until now, but to keep a consistent formatting, I suggest to reformat at least this sld with e.g.
> 
> xmllint --output mdbw_transit_stops_default.sld --format mdbw_transit_stops_default.sld.
> 
> Note to self: For other slds and xml files, we should lint them in an explicit commit and add linting to the github actions.

**Pull request merged**
