### PR TITLE
major park-api upgrade

### PR DESCRIPTION
**Pull request by the-infinity**
Major park-api update. Requires https://github.com/mobidata-bw/ipl-ansible/pull/46 to be merged / used during deployment.

### CODE REVIEW

**Review by hbruch — CHANGES_REQUESTED** [review]
Could you please create a `CHANGELOG` file which describes the high-level functional changes of this new major update? And as this PR removes `PARK_API_CONVERTER` configuration: where does this configuration happen in the future?

**Comment by the-infinity** [comment]
`PARK_API_CONVERTER` was moved to the secrets file as it containes credentials now (secrets for api access, basicauth credentials).

**Comment by the-infinity** [comment]
> Could you please create a `CHANGELOG` file which describes the high-level functional changes of this new major update? And as this PR removes `PARK_API_CONVERTER` configuration: where does this configuration happen in the future?

Added Changelog to ParkAPI project. As there were no releases before, it's a rather short summary.

**Comment by the-infinity** [comment]
Added changelog entries in this project.

**Comment by hbruch** [comment]
LGTM

**Review by hbruch — APPROVED** [review]

**Pull request merged**
